### ISSUE TITLE
visualizerってどうやって使うの...???

### ISSUE THREAD

**Issue by p623** [p623/google-step-tsp#7]

**Comment by hayatoito** [comment]
Web サーバを自分のPC上で起動する必要があります！
起動するには、ターミナル等で:

```
# clone したディレクトリに移動して （ここ重要）
cd google-step-tsp
# Web サーバを起動 (Python に付属しています）
python3 -m http.server
```

そしてその後、ブラウザ (Google Chrome 等)で `http://localhost:8000/visualizer/build/default/'
（この URL をブラウザにアドレス欄に コピペします） にアクセスします。

すると、見れるはず？

その後（例えば）
Challenges: `0`
Output: `Your output` 

を選択すると、output_0.csv ファイルのルートをビジュアライズしてくれます。

**Comment by hayatoito** [comment]
`python3 -m http.server` で起動するWeb サーバだとうまく動かないという報告が...。のちほど。

**Comment by hayatoito** [comment]
Ruby内蔵の Web サーバだと動くかも？ もし `python3 -m http.server` でだめなときは、こちらを試してみてください。
`ruby -run -ehttpd . -p8000`

大変失礼しました！

**Comment by p623** [comment]
visualizerはrubyの方のコマンドで起動することができましたが、outputのcsvを書き換えたら、visualizerで動かすことが出来なくなってしまいました...????

**Comment by p623** [comment]
大丈夫でした。各点のインデックス、0からなんですね...お騒がせしました...
