### ISSUE TITLE
ねね、今気がついたんだけど

### ISSUE THREAD

**Issue by p623** [p623/google-step-tsp#8]
google-step-tspのsolver_greedy.pyとかsolver_random.pyみたいなサンプルある笑
全然気づかなかった笑

あと、inoNBikkuri.pyもsolver_greedy.pyみたいに、$python solver_greedy.py input_0.csvみたいに
$python inoNBikkuri.py input_0.csvってやったら実行されるようにしたいんだけど、誰かわかる人やって笑

あと、焼きなまし法(?)って初期値をいい感じの小さい値(極小値)にしたら、より小さないい感じの値を導いてくれたりする?
もしそうなら、まずgreedy法で極小値を求めて、それを初期値として焼きなまししたら何となくいい感じになるのかなあと思ったんだけど...

**Comment by KyokoMuto** [comment]
ありがとう！
ちなみに、出た値って極小値っぽかった、、、？
それなら、PとかTの値に関しては問題なさそう！

**Comment by KyokoMuto** [comment]
初期値に関してだけど、一度やったときはランダムな値を複数回とってそこの最小値から焼きなまししたたんだけど、greedyでもとめたアルゴリズムと焼きなましでもとめていくアルゴリズムがちがうならだけど、ある意味別の極小値を求めてくれるなら初期値にしてもいいのかなあと思った（どうせgreedy求めるなら）！

**Comment by p623** [comment]
hill climb ver.でも焼きなまし ver.でもinput_1.csvで10回くらいやってみて
トータル距離が3778.715416か3832.290094しかでなかったから極小値っぽいのかなあとは思ったんだけど、正直出た値が極小値か否かはよくわからないや...

今のコードの仕様だと、最初の都市の巡り方をランダムに決める→hill climb or 焼きなましで最適化→greedyより結果が悪かったら、この繰り返しをもう一回やるって感じで実装しているんだけど、この最初のランダムな経路がその経路から最も近い極小値を取る経路からどれだけ遠いのかによって極小値にたどり着くまでにかかる時間が変わってくるから、たどり着けないで終わるっていうのもある気がするし...

greedyを初期値にするか否かっていうのは今の実装の感じ(上記)からあんまり効率の良さに関係ない気がした...
(自分で聞いといて本当にごめん...笑)

なんかhill climb より焼きなましの方が重いのなんでなんだろう...
あと、この関数呼びすぎ！ってエラーってどうしたらいいんや...
巡らなきゃいけない都市の増加に伴って、極小値の数が増えるから、greedyよりも大きな極小値が増えてこのエラーが起こってしまうと思うんだけど、その対応策がわからん...

誰か、教えて...

**Comment by hayatoito** [comment]
おつかれさまです！

https://github.com/p623/google-step-tsp/commit/7f39fac12a70e9e6a28cfb85119654dd4c098d3a でコメントしたんですけど、困っているっぽいので、ここでもコメントしますね。

ここだけ:
> あと、この関数呼びすぎ！ってエラーってどうしたらいいんや...

stackoverflow です。たとえば、

```python

def foo(a):
    if a == 1000000:
      return a
    return a + foo(a + 1)

print(foo(0))
```
のような感じで、foo() の中からさらにfoo() を呼び出すと、foo() は 1000000回呼ばれるのですが、このとき"今のfoo()" が終わらないうちに、"次のfoo()" を呼び出すことになります。

このとき、Python の処理系は、
```
foo(0)
  => foo(1)
    => foo(2)
      => foo(3)
        => foo(4)
          => ...
```
と途中の関数の呼び出し状態をすべて覚えておかないといかません。このような関数の呼び出しの入れ子状態（コールスタックといいます）を覚えておくたには、一般にメモリの中の`スタック` (Stack) という領域を使用するのですが、Stack はサイズは限られているため、再帰呼出しの回数が一定以上になるとスタックが足りなくなりエラーになります。

解決方法は再帰呼出しはやめて、
```python

def foo(a):
    sum = 0
    while True:
        if a == 1000000:
            return sum
        sum += a
        a += 1

print(foo(0))
```

などのように、ループにするとよいと思います！

inoYaki.py の場合は、まさに `annealingoptimize` 関数が 上記fooと同じような再帰呼び出しの構造になっていますので、再帰呼び出しはやめて ただのループに書き直すとよいと思います！

**Comment by p623** [comment]
すみません、Itoさん、コメントについさっき気づきました...。
直せるところは直したのですが、N=64以上で常に(?)breakしてしまいます...(なぜだか私にはわからない...)
焼きなまし法っぽいのを考えると初期値から初期値の近傍にずらすorずらさないをしなきゃいけないので、ランダムに選んだ2点を入れ替えるor入れ替えないより、一点をランダムに選んで、そのそばの一点と交換するorしないみたいなのを書いた方がいいのかなと思いました...
誰か、上記の問題点を改善(?)できる人いましたらお願いします！！！

**Comment by p623** [comment]
上で言ってた一点をランダムに選んで、そのそばの一点と交換するorしないみたいにやる焼きなまし法をinoYaki2.pyとしてつくってみました
でもN=64以上で常にbreakしてしまうのが改善できてないので、今日のoffice hourとかで改善してもらえると嬉しいです!正直、焼きなまし法とかのやり方もこのコードでちゃんと書けているのかわかってないので、見てもらえると嬉しいです!!!

**Comment by hayatoito** [comment]
りょうかいです！office hour で見ますね！

**Comment by KyokoMuto** [comment]
そういえば、greedyからhillちょっとやってみたけど、greedyに比べたら少し改善するくらいだったから、去年のとかみたいに大きく数字が小さくなることはなかった、、
焼きなまし法も少し修正してみたけど、いい値はあんまりでなさそうだったからなんか違うのかなと思って挙げてない、、

**Comment by hayatoito** [comment]
今日の office hours で森ビルの受付で入館証をもらうために、必要な情報です。

入館予約番号：0611
＜変更内容詳細＞
ご来訪者：Team Python 4    Kyoko Muto 様  他5名
ご訪問先：グーグル合同会社    Hayato Ito
訪問先：44F
ご来訪日時：2018/6/26 18:00

あと、重要な情報として、Google の 44F の受付は 18:00で 閉まってしまいます。44F でエレベータを降りて、受付に向かおうとしても、扉がしまっている可能性があります！

ですので、18:05 くらいにいったん44Fのエレベータを降りたところに迎えにいきますね。
もし、遅れる、または早く到着した等があったら、連絡ください。迎えにいきます。

**Comment by nasama** [comment]
焼きなましのannealingoptimize関数の温度TをT=100000と高くして、coolをcool=0.9999に変更すると、焼きなましが最適化されました。
N = 64 で break しないようにするために、while T>0.0001: のループの前にT = 100000を付け加えて、Tを初期化する必要がありました。
